<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="12688" started-at="2019-05-21T07:18:34Z" finished-at="2019-05-21T07:18:47Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="12688" started-at="2019-05-21T07:18:34Z" finished-at="2019-05-21T07:18:47Z">
      <class name="com.inetbanking.testcase.TC_LoginDDT_002">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.inetbanking.testcase.TC_LoginDDT_002@61832929]" name="setup" is-config="true" duration-ms="11969" started-at="2019-05-21T12:48:34Z" finished-at="2019-05-21T12:48:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="LoginDDt(java.lang.String, java.lang.String)[pri:0, instance:com.inetbanking.testcase.TC_LoginDDT_002@61832929]" name="LoginDDt" duration-ms="0" started-at="2019-05-21T12:48:46Z" data-provider="LoginData" finished-at="2019-05-21T12:48:46Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void com.inetbanking.testcase.TC_LoginDDT_002.LoginDDt(java.lang.String,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : LoginData]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void com.inetbanking.testcase.TC_LoginDDT_002.LoginDDt(java.lang.String,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : LoginData
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginDDt -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.inetbanking.testcase.TC_LoginDDT_002@61832929]" name="tearDown" is-config="true" duration-ms="704" started-at="2019-05-21T12:48:46Z" finished-at="2019-05-21T12:48:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.inetbanking.testcase.TC_LoginDDT_002 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
